environment:
  matrix:
    - PYTHON: "C:\\Python27"

# branches to build
branches:
  # whitelist
  # only:
  #   - master
  #   - production

  # blacklist
  except:
    - gh-pages  
    
cache:
  - '%PYTHON%\Lib\site-packages'
 
install:
  # - ps: Start-FileDownload "https://github.com/appveyor/ci/raw/master/scripts/enable-rdp.ps1" -Timeout 60000
  # - enable-rdp.ps1
  
  - ps: Start-FileDownload "http://www.innosetup.com/download.php/is-unicode.exe" -Timeout 60000 -FileName "is-unicode.exe"
  - cmd: is-unicode.exe /SP /VERYSILENT /SUPPRESSMSGBOXES /NORESTART /RESTARTAPPLICATIONS /NOICONS

  - ps: Start-FileDownload "http://www.stackless.com/binaries/python-2.7.12150-stackless.msi" -Timeout 60000 -FileName "stackless-setup.msi"
  - cmd: stackless-setup.msi /quiet /passive /qn /norestart

  - cmd: pip install commonmark==0.7.0
  - cmd: pip install https://github.com/enthought/comtypes/archive/1.1.2.zip
  - cmd: pip install https://eventghost.github.io/dist/dependencies/ctypeslib-0.5.6-cp27-none-any.whl
  - cmd: pip install future==0.15.2
  - cmd: pip install pillow==3.1.1
  - cmd: pip install py2exe_py2==0.6.9
  - cmd: pip install pycrypto==2.6.1
  # - cmd: pip install https://eventghost.github.io/dist/dependencies/pywin32-220-cp27-none-win32.whl
  - cmd: pip install pypiwin32==219
  - cmd: pip install sphinx==1.3.5
  - cmd: pip install https://eventghost.github.io/dist/dependencies/wxPython-3.0.2.0-cp27-none-win32.whl

build: off

test_script:
  - cmd: python.exe _build\\Build.py --build --package
  - cmd: echo "##################------------------####################"

after_test:
  # - dir _build\output\*.exe /B > setup-exe.txt
  # - set /P setup-exe= < setup-exe.txt
  # - START /WAIT %setup-exe% /VERYSILENT /SUPPRESSMSGBOXES /NOCLOSEAPPLICATIONS
  

artifacts:
  - path: "_build\\output\\*Setup.exe"
